# LISTAR todas companhias:
GET http://localhost:3000/companhias
###

# LISTAR uma companhia por id:
GET http://localhost:3000/companhias/1
###

# CADASTRAR uma nova companhia:
POST http://localhost:3000/companhias
Content-Type: application/json

{
    "nome":"LATAM"    
}
###

# EXCLUIR companhia por id:
DELETE http://localhost:3000/companhias/2
###